version: 2

jobs:
  build:
    docker:
      - image: mbgl/ci:r4-linux-gl-js
    working_directory: ~/mapbox-gl-js
    steps:
      - checkout
      - restore_cache:
          key: v1-mapbox-gl-js-cache
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          key: v1-mapbox-gl-js-cache
          paths:
            - '~/.yarn'
            - '.eslintcache'
            - 'node_modules'
      - run:
          name: run tests
          command: |
            bash ./.circleci/test.sh
      - store_artifacts:
          path: "test/integration/render-tests/index.html"
      - store_artifacts:
          path: "test/integration/query-tests/index.html"
      - run:
          name: deploy if tagged
          when: on_success
          command: |
            if [[ $CIRCLE_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+(\-dev)? ]]; then
              bash ./.circleci/deploy.sh
            fi
# this is a workaround for getting the CIRCLE_TAG env variable to work in 2.0
# ref: https://discuss.circleci.com/t/build-on-tag/9864/42
deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    steps:
      - run: echo "make tags run in 2.0"
